default: &default
  adapter: postgresql
  encoding: utf8
  host: <%= ENV["DATABASE_HOST"] %>
  pool: <%= ENV["DATABASE_POOL_SIZE"] %>
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  database: <%= ENV["DATABASE_NAME"] %>

development:
  <<: *default

test:
  <<: *default
  database: <%= ENV["TEST_DATABASE_NAME"] %>

production:
  <<: *default
